apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv1-zaznam-chorob-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /cv1-zaznam-chorob-openapi
            - name: BASE_URL
              value: /cv1-zaznam-chorob-openapi-ui