apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cv1-zaznam-chorob-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/bartalos86/WAC-zaznam-chorob-gitops

# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: <pfx>-repository-pat