apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1-zaznam-chorob-ufe-content
spec:
  microFrontend: cv1-zaznam-chorob-ufe
  element: patient-app
  attributes:
    - name: api-base
      value: /cv1-zaznam-chorob-api
    - name: base-path
      value: /cv1-zaznam-chorob/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1-zaznam-chorob(/.*)?$"