apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: cv1-zaznam-chorob
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/cv1-zaznam-chorob-ufe
- ../../../apps/cv1-zaznam-chorob-webapi


components:
- ../../../components/version-release