apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital  # chceme tieto objekty umiestniť do `wac-hospital` namespace
                         # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch
labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/cv1-zaznam-chorob-ufe
# - ../../../apps/cv1-zaznam-chorob-webapi
# - ../../../apps/polyfea-md-shell

patches:
# - path: patches/material-design.microfrontend.yaml
# - path: patches/polyfea-md-shell.microfrontend.yaml
- path: patches/ambulance-webapi.service.yaml
- path: patches/polyfea-fea.microfrontendclass.yaml

components:
- ../../../components/version-developers
# - https://github.com/bartalos86/WAC-zaznam-chorob-webapi//deployments/kustomize/components/mongodb
